#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mpir
Version  : 3.0.0
Release  : 2
URL      : https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz
Source0  : https://github.com/wbhart/mpir/archive/mpir-3.0.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0 LGPL-3.0
Requires: mpir-info = %{version}-%{release}
Requires: mpir-lib = %{version}-%{release}
Requires: mpir-license = %{version}-%{release}
BuildRequires : automake
BuildRequires : automake-dev
BuildRequires : gettext-bin
BuildRequires : libtool
BuildRequires : libtool-dev
BuildRequires : m4
BuildRequires : pkg-config-dev
BuildRequires : texinfo
BuildRequires : yasm
Patch1: 0001-Build-fixes.patch

%description
This file is part of the MPIR Library.
The MPIR Library is free software; you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation; either version 3 of the License, or (at your
option) any later version.

%package dev
Summary: dev components for the mpir package.
Group: Development
Requires: mpir-lib = %{version}-%{release}
Provides: mpir-devel = %{version}-%{release}
Requires: mpir = %{version}-%{release}

%description dev
dev components for the mpir package.


%package info
Summary: info components for the mpir package.
Group: Default

%description info
info components for the mpir package.


%package lib
Summary: lib components for the mpir package.
Group: Libraries
Requires: mpir-license = %{version}-%{release}

%description lib
lib components for the mpir package.


%package license
Summary: license components for the mpir package.
Group: Default

%description license
license components for the mpir package.


%prep
%setup -q -n mpir-mpir-3.0.0
cd %{_builddir}/mpir-mpir-3.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1573790090
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%autogen --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1573790090
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/mpir
cp %{_builddir}/mpir-mpir-3.0.0/COPYING %{buildroot}/usr/share/package-licenses/mpir/8624bcdae55baeef00cd11d5dfcfa60f68710a02
cp %{_builddir}/mpir-mpir-3.0.0/COPYING.LIB %{buildroot}/usr/share/package-licenses/mpir/e203d4ef09d404fa5c03cf6590e44231665be689
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/mpir.h
/usr/lib64/libmpir.so

%files info
%defattr(0644,root,root,0755)
/usr/share/info/mpir.info
/usr/share/info/mpir.info-1
/usr/share/info/mpir.info-2

%files lib
%defattr(-,root,root,-)
/usr/lib64/libmpir.so.23
/usr/lib64/libmpir.so.23.0.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mpir/8624bcdae55baeef00cd11d5dfcfa60f68710a02
/usr/share/package-licenses/mpir/e203d4ef09d404fa5c03cf6590e44231665be689
